version: '3.7'

# 使用已存在的 traefik 的 network
networks:
  traefik-proxy-network:
    # external: true # 外部，此处都是同个 docker-compose 文件 无需开启
    name: proxy-net # 指定名称

services:
  traefik:
    container_name: traefik
    image: traefik:v2.5
    ports:
      - "80:80"
      - "443:443" # 用于 TLS 即 HTTPS
      - "8080:8080"
    networks: # 指定 network
      - traefik-proxy-network
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
      - ./log:/log
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    # labels:
      # - "traefik.enable=true" # 如果要在 面板上看到 traefik 服务，则开启

  nuxt:
    restart: always
    container_name: nuxt
    build:
      context: ./nuxt/
    ports:
      - 3000:3000
    networks: # 指定 network
      - traefik-proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt.rule=PathPrefix(`/`)"
      # - "traefik.http.routers.nuxt.tls=true" # 开启 https 
      # - "traefik.http.routers.nuxt.tls.certresolver=le"
