version: '3.7'

# 使用已存在的 traefik 的 network
networks:
  traefik-proxy-network:
    external: true # 使用已存在、组合（compose 文件）之外的 network，如果不存在则提示 network proxy-net declared as external, but could not be found
    name: proxy-net # 指定名称

services:
  nuxt:
    restart: always
    container_name: nuxt
    build:
      context: ./nuxt/
    networks: # 指定 network 使这个容器成为该网络的一部分
      - traefik-proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt.rule=PathPrefix(`/`)"
      # - "traefik.http.routers.nuxt.tls=true" # 开启 https
      # - "traefik.http.routers.nuxt.tls.certresolver=le"
